- name: Check if loginmonitor is installed
  shell: ls /var/db/newrelic-infra/custom-integrations | grep campaign-loginmonitor-definition.yml
  register: check_loginmonitor
  ignore_errors: true

- name: Change the directory to where the .logimonitor is present
  shell: >
      cd /var/db/newrelic-infra/custom-integrations;
      /etc/newrelic-infra/custom-integrations/bin/campaign-loginmonitor acc |
      grep -oP '{.*}' | python -c "import sys; print(str(sys.stdin.read().split('\n')[-2]))"
  register: loginmonitor_status

- name: Extract response code from the JSON output
  shell: echo "{{ (loginmonitor_status.stdout | from_json).metrics[0].responseCode }}"
  register: response

- name: Verify if response code is 200 
  debug:
    msg: "{{ response.stdout }}"
  failed_when: '"200" not in response.stdout'
  

