- name: Enable MAC integration on RT instance per instance
  block:
  - name: include ims client id and secret
    include_vars: vault_v6.yml

  - name: Set facts
    set_fact:
        orgId: "{{ org_id }}"
        associationMask: "Campaign - {{ tenant_id + rt_instance_type }} - (.*)"
        product_context: 'dma_campaign_classic'
        tenant: "{{ tenant }}" 
        serverUrl: "{{ server_url }}"

  - name: Install MAC integration package
    shell: nlserver package -instance:{{ instance_name }} -force -import:/usr/local/neolane/nl{{ nlversion }}/datakit/nms/eng/package/macIntegration.xml
    environment: "{{ neolane_env }}"

  - name: check if mac external account details present in db after macIntegration installation
    shell: |
      eval `camp-db-params -e`
      psql -tc "select count(*) from nmsextaccount where sclientid='Campaign1' and simsserver='https://adobeid-na1.services.adobe.com' and sserver='https://marketing.adobe.com' and slabel='MAC' and itype=13;"
    become: yes
    register: psql_result_macIntegration

  - name: Fail task if row count is zero
    fail:
      msg: "Row count for macIntegration in nmsextaccount is zero"
    when: psql_result_macIntegration.stdout|int == 0

  - name: copy ims v6 js
    template:
      src: set_ims_v6.js.j2
      dest: /tmp/set_ims_v6.js

  - name: Execute JS for setting up IMS
    shell: nlserver javascript -instance:"{{ instance_name }}" -file /tmp/set_ims_v6.js
    environment: "{{ neolane_env }}"

  - name: check if mac external account details present in db after mac account configuration
    shell: |
      eval `camp-db-params -e`
      psql -tc "select count(*) from nmsextaccount where sclientid='Campaign1' and simsserver='https://adobeid-na1.services.adobe.com' and sproductcontext='dma_campaign_classic' and sserver='https://marketing.adobe.com' and slabel='MAC' and itype=13 and sclientsecret IS NOT NULL and scallbackserver like '%.campaign.adobe.com' and simsorgid like '%@AdobeOrg' and simsrightsmask='{{ associationMask }}';"
    become: yes
    register: psql_result

  - name: Fail task if row count is zero
    fail:
      msg: "Row count for mac account configuration in nmsextaccount is zero"
    when: psql_result.stdout|int == 0

  - name: Cleaning up
    file:
      dest: /tmp/set_ims_v6.js
      state: absent
  when: inventory_hostname is search("^.*-(mkt|mid|rt)-.*$") and inventory_hostname is search("^.*-1$")
